components:
  schemas:
    Producto:
      type: object
      required:
        - nombre
        - descripcion
        - stock
        - precio
        - estado
      properties:
        nombre:
          type: string
        descripcion:
          type: string
        stock:
          type: number
        precio:
          type: string
        proveedor:
          $ref: "#/components/schemas/Proveedor"
        usuario:
          $ref: "#/components/schemas/Usuario"
        estado:
          type: string
          enum: ["ACTIVO", "INACTIVO"]
          default: "ACTIVO"
